import type { Product } from "@/types/product";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Classic Heavyweight Tee",
    brand: "Nike",
    category: "tops",
    price: 45,
    originalPrice: 60,
    images: ["/products/product-1.png", "/products/product-1.png"],
    sizes: ["S", "M", "L", "XL"],
    isNew: true,
    inStock: true,
    rating: 4.8,
    reviewCount: 124,
  },
  {
    id: "2",
    name: "Raw Denim Slim Fit",
    brand: "Adidas",
    category: "bottoms",
    price: 120,
    images: ["/products/product-2.png", "/products/product-2.png"],
    sizes: ["30", "32", "34"],
    isNew: false,
    inStock: true,
    rating: 4.5,
    reviewCount: 89,
  },
  {
    id: "3",
    name: "Technical Shell Jacket",
    brand: "Puma",
    category: "outerwear",
    price: 210,
    originalPrice: 295,
    images: ["/products/product-3.png", "/products/product-3.png"],
    sizes: ["M", "L"],
    isNew: false,
    inStock: false,
    rating: 4.9,
    reviewCount: 42,
  },
  {
    id: "4",
    name: "Classic Heavyweight Tee",
    brand: "Nike",
    category: "tops",
    price: 45,
    originalPrice: 60,
    images: ["/products/product-1.png", "/products/product-1.png"],
    sizes: ["S", "M", "L", "XL"],
    isNew: true,
    inStock: true,
    rating: 4.8,
    reviewCount: 124,
  },
  {
    id: "5",
    name: "Raw Denim Slim Fit",
    brand: "Adidas",
    category: "bottoms",
    price: 120,
    images: ["/products/product-2.png", "/products/product-2.png"],
    sizes: ["30", "32", "34"],
    isNew: false,
    inStock: true,
    rating: 4.5,
    reviewCount: 89,
  },
  {
    id: "6",
    name: "Technical Shell Jacket",
    brand: "Puma",
    category: "outerwear",
    price: 210,
    originalPrice: 295,
    images: ["/products/product-3.png", "/products/product-3.png"],
    sizes: ["M", "L"],
    isNew: false,
    inStock: false,
    rating: 4.9,
    reviewCount: 42,
  },
];
