import type { Product } from "@/types/product";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Classic Heavyweight Tee",
    brand: "Nike",
    category: "tops",
    price: 45,
    originalPrice: 60,
    images: ["/products/product-1.png", "/products/product-1.png"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["navy", "white", "red"],
    isNew: true,
    inStock: true,
    rating: 4.8,
    reviewCount: 124,
  },
  {
    id: "2",
    name: "Raw Denim Slim Fit",
    brand: "Adidas",
    category: "bottoms",
    price: 120,
    images: ["/products/product-2.png", "/products/product-2.png"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["blue", "navy", "white"],
    isNew: false,
    inStock: true,
    rating: 4.5,
    reviewCount: 89,
  },
  {
    id: "3",
    name: "Technical Shell Jacket",
    brand: "Puma",
    category: "outerwear",
    price: 210,
    originalPrice: 295,
    images: ["/products/product-3.png", "/products/product-3.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["mint", "aqua", "purple"],
    isNew: false,
    inStock: false,
    rating: 4.9,
    reviewCount: 42,
  },
  {
    id: "4",
    name: "Urban Oversized Tee",
    brand: "Nike",
    category: "tops",
    price: 65,
    originalPrice: 79,
    images: ["/products/product-4.png", "/products/product-4.png"],
    sizes: ["XXS", "XS", "S", "M", "L"],
    colors: ["yellow", "orange", "red"],
    isNew: true,
    inStock: true,
    rating: 4.7,
    reviewCount: 66,
  },
  {
    id: "5",
    name: "Relaxed Cargo Pants",
    brand: "Adidas",
    category: "bottoms",
    price: 98,
    images: ["/products/product-5.png", "/products/product-5.png"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["navy", "mint", "sky"],
    isNew: false,
    inStock: true,
    rating: 4.4,
    reviewCount: 53,
  },
  {
    id: "6",
    name: "Storm Utility Jacket",
    brand: "Puma",
    category: "outerwear",
    price: 240,
    originalPrice: 320,
    images: ["/products/product-6.png", "/products/product-6.png"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["navy", "sky", "blue"],
    isNew: false,
    inStock: false,
    rating: 4.9,
    reviewCount: 71,
  },
];
